"use client"
import "./globals.css";
import {Provider} from 'react-redux'
import {store} from '@/store/store'
import { useEffect, useState} from 'react'

// export const metadata = {
//   title: "Belajar React Sinau Koding",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  const [isClient, setIsClient] = useState(false)

  useEffect(() => {
    setIsClient(true)
  }, [])

  return (
    <html lang="en">
      <body>
        {isClient ? (
          <Provider store={store}>
            {children}
          </Provider>
        ) : null}
      </body>
    </html>
  )
}